REPLACE INTO `command` VALUES ('account', 1, 'Syntax: .account\r\n\r\nDisplay the access level of your account and the email adress if you possess the necessary permissions.');
REPLACE INTO `command` VALUES ('account addon', 3, 'Syntax: .account addon #addon\nSet expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk.');
REPLACE INTO `command` VALUES ('account create', 3, 'Syntax: .account create $account $password\r\n\r\nCreate account and set password to it.');
REPLACE INTO `command` VALUES ('account delete', 9, 'Syntax: .account delete $account\r\n\r\nDelete account with all characters.');
REPLACE INTO `command` VALUES ('account lock country', 0, 'Syntax: .account lock country [on|off]\nAllow login from account only from current used Country or remove this requirement.');
REPLACE INTO `command` VALUES ('account lock ip', 0, 'Syntax: .account lock ip [on|off]\nAllow login from account only from current used IP or remove this requirement.');
REPLACE INTO `command` VALUES ('account onlinelist', 5, 'Syntax: .account onlinelist\r\n\r\nShow list of online accounts.');
REPLACE INTO `command` VALUES ('account password', 1, 'Syntax: .account password $old_password $new_password $new_password [$email]\r\n\r\nChange your account password. You may need to check the actual security mode to see if email input is necessary.');
REPLACE INTO `command` VALUES ('account set', 3, 'Syntax: .account set $subcommand\nType .account set to see the list of possible subcommands or .help account set $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('account set addon', 3, 'Syntax: .account set addon [$account] #addon\r\n\r\nSet user (possible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk.');
REPLACE INTO `command` VALUES ('account set gmlevel', 9, 'Syntax: .account set gmlevel [$account] #level [#realmid]\r\n\r\nSet the security level for targeted player (can\'t be used at self) or for account $name to a level of #level on the realm #realmID.\r\n\r\n#level may range from 0 to 3.\r\n\r\n#reamID may be -1 for all realms.');
REPLACE INTO `command` VALUES ('account set password', 9, 'Syntax: .account set password $account $password $password\r\n\r\nSet password for account.');
REPLACE INTO `command` VALUES ('achievement', 9, 'Syntax: .achievement $subcommand\nType .achievement to see the list of possible subcommands or .help achievement $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('achievement add', 9, 'Syntax: .achievement add $achievement\nAdd an achievement to the targeted player.\n$achievement: can be either achievement id or achievement link');
REPLACE INTO `command` VALUES ('achievement checkall', 9, '');
REPLACE INTO `command` VALUES ('additem', 6, 'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\n\r\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added.\r\n.');
REPLACE INTO `command` VALUES ('additemset', 6, 'Syntax: .additemset #itemsetid\r\n\r\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.');
REPLACE INTO `command` VALUES ('announce', 4, 'Syntax: .announce $MessageToBroadcast\r\n\r\nSend a global message to all players online in chat log.');
REPLACE INTO `command` VALUES ('appear', 1, 'Syntax: .appear [$charactername]\r\n\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait,e.g. when you are in a group. Character can be offline.');
REPLACE INTO `command` VALUES ('arena captain', 7, 'Syntax: .arena captain #TeamID $name\n\nA command to set new captain to the team $name must be in the team');
REPLACE INTO `command` VALUES ('arena create', 7, 'Syntax: .arena create $name "arena name" #type\n\nA command to create a new Arena-team in game. #type  = [2/3/5]');
REPLACE INTO `command` VALUES ('arena disband', 7, 'Syntax: .arena disband #TeamID\n\nA command to disband Arena-team in game.');
REPLACE INTO `command` VALUES ('arena info', 7, 'Syntax: .arena info #TeamID\n\nA command that show info about arena team');
REPLACE INTO `command` VALUES ('arena lookup', 7, 'Syntax: .arena lookup $name\n\nA command that give a list of arenateam with the given $name');
REPLACE INTO `command` VALUES ('arena rename', 7, 'Syntax: .arena rename "oldname" "newname"\n\nA command to rename Arena-team name.');
REPLACE INTO `command` VALUES ('aura', 8, 'Syntax: .aura #spellid\r\n\r\nAdd the aura from spell #spellid to the selected Unit.');
REPLACE INTO `command` VALUES ('ban', 5, 'Syntax: .ban $subcommand\nType .ban to see the list of possible subcommands or .help ban $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('ban account', 5, 'Syntax: .ban account $Name $bantime $reason\r\nBan account kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".');
REPLACE INTO `command` VALUES ('ban character', 5, 'Syntax: .ban character $Name $bantime $reason\nBan character and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".');
REPLACE INTO `command` VALUES ('ban ip', 5, 'Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".');
REPLACE INTO `command` VALUES ('ban playeraccount', 5, 'Syntax: .ban playeraccount $Name $bantime $reason\nBan account and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".');
REPLACE INTO `command` VALUES ('baninfo', 5, 'Syntax: .baninfo $subcommand\nType .baninfo to see the list of possible subcommands or .help baninfo $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('baninfo account', 5, 'Syntax: .baninfo account $accountid\r\nWatch full information about a specific ban.');
REPLACE INTO `command` VALUES ('baninfo character', 5, 'Syntax: .baninfo character $charactername \r\nWatch full information about a specific ban.');
REPLACE INTO `command` VALUES ('baninfo ip', 5, 'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ban.');
REPLACE INTO `command` VALUES ('banlist', 5, 'Syntax: .banlist $subcommand\nType .banlist to see the list of possible subcommands or .help banlist $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('banlist account', 5, 'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.');
REPLACE INTO `command` VALUES ('banlist character', 5, 'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern. Pattern required.');
REPLACE INTO `command` VALUES ('banlist ip', 5, 'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.');
REPLACE INTO `command` VALUES ('bf', 8, '');
REPLACE INTO `command` VALUES ('bf enable', 8, 'Syntax: .bf enable #battleid');
REPLACE INTO `command` VALUES ('bf start', 8, 'Syntax: .bf start #battleid');
REPLACE INTO `command` VALUES ('bf stop', 8, 'Syntax: .bf stop #battleid');
REPLACE INTO `command` VALUES ('bf switch', 8, 'Syntax: .bf switch #battleid');
REPLACE INTO `command` VALUES ('bf timer', 8, 'Syntax: .bf timer #battleid #timer');
REPLACE INTO `command` VALUES ('bindsight', 7, 'Syntax: .bindsight\r\n\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.');
REPLACE INTO `command` VALUES ('cast', 8, 'Syntax: .cast #spellid [triggered]\r\n  Cast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.');
REPLACE INTO `command` VALUES ('cast back', 8, 'Syntax: .cast back #spellid [triggered]\r\n  Selected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.');
REPLACE INTO `command` VALUES ('cast dest', 8, 'Syntax: .cast dest #spellid #x #y #z [triggered]\r\n  Selected target will cast #spellid at provided destination. If \'trigered\' or part provided then spell casted with triggered flag.');
REPLACE INTO `command` VALUES ('cast dist', 8, 'Syntax: .cast dist #spellid [#dist [triggered]]\r\n  You will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.');
REPLACE INTO `command` VALUES ('cast self', 8, 'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.');
REPLACE INTO `command` VALUES ('cast target', 8, 'Syntax: .cast target #spellid [triggered]\r\n  Selected target will cast #spellid to his victim. If \'trigered\' or part provided then spell casted with triggered flag.');
REPLACE INTO `command` VALUES ('character', 6, 'Syntax: character $subcommand\n Type .character to see a list of possible subcommands\n or .help character $subcommand to see info on the subcommand.');
REPLACE INTO `command` VALUES ('character changefaction', 6, 'Syntax: .character changefaction $name\r\n\r\nChange character faction.');
REPLACE INTO `command` VALUES ('character changerace', 6, 'Syntax: .character changerace $name\r\n\r\nChange character race.');
REPLACE INTO `command` VALUES ('character customize', 6, 'Syntax: .character customize [$name]\r\n\r\nMark selected in game or by $name in command character for customize at next login.');
REPLACE INTO `command` VALUES ('character deleted delete', 9, 'Syntax: .character deleted delete #guid|$name\r\n\r\nCompletely deletes the selected characters.\r\nIf $name is supplied, only characters with that string in their name will be deleted, if #guid is supplied, only the character with that GUID will be deleted.');
REPLACE INTO `command` VALUES ('character deleted list', 9, 'Syntax: .character deleted list [#guid|$name]\r\n\r\nShows a list with all deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be selected, if #guid is supplied, only the character with that GUID will be selected.');
REPLACE INTO `command` VALUES ('character deleted old', 9, 'Syntax: .character deleted old [#keepDays]\r\n\r\nCompletely deletes all characters with deleted time longer #keepDays. If #keepDays not provided the  used value from mangosd.conf option \'CharDelete.KeepDays\'. If referenced config option disabled (use 0 value) then command can\'t be used without #keepDays.');
REPLACE INTO `command` VALUES ('character deleted restore', 9, 'Syntax: .character deleted restore #guid|$name [$newname] [#new account]\r\n\r\nRestores deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be restored, if $guid is supplied, only the character with that GUID will be restored.\r\nIf $newname is set, the character will be restored with that name instead of the original one. If #newaccount is set, the character will be restored to specific account character list. This works only with one character!');
REPLACE INTO `command` VALUES ('character erase', 9, 'Syntax: .character erase $name\r\n\r\nDelete character $name. Character finally deleted in case any deleting options.');
REPLACE INTO `command` VALUES ('character level', 6, 'Syntax: .character level [$playername] [#level]\r\n\r\nSet the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.');
REPLACE INTO `command` VALUES ('character rename', 6, 'Syntax: .character rename [$name] [$newName] \n\nMark selected in game or by $name in command character for rename at next login.\n\nIf $newName then the player will be forced rename.');
REPLACE INTO `command` VALUES ('character reputation', 6, 'Syntax: .character reputation [$player_name]\r\n\r\nShow reputation information for selected player or player find by $player_name.');
REPLACE INTO `command` VALUES ('character titles', 6, 'Syntax: .character titles [$player_name]\r\n\r\nShow known titles list for selected player or player find by $player_name.');
REPLACE INTO `command` VALUES ('cheat', 8, 'Syntax: .cheat $subcommand\r\nType .cheat to see the list of possible subcommands or .help cheat $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('cheat casttime', 8, 'Syntax: .cheat casttime [on/off]\r\nRemove spells\' casting time.');
REPLACE INTO `command` VALUES ('cheat cooldown', 8, 'Syntax: .cheat cooldown [on/off]\r\nDisable spells\' cooldowns.');
REPLACE INTO `command` VALUES ('cheat god', 8, 'Syntax: .cheat god [on/off]\r\nTurn the user invulnerable.');
REPLACE INTO `command` VALUES ('cheat power', 8, 'Syntax: .cheat power [on/off]\r\nRemove spells\' cost (mana, energy, rage...).');
REPLACE INTO `command` VALUES ('cheat taxi', 8, 'Syntax: .cheat taxi on/off\r\nTemporary grant access to all taxi routes for the selected character.\r\n If no character is selected, hide or reveal all routes to you. Visited taxi nodes are still accessible after removing access.');
REPLACE INTO `command` VALUES ('cheat waterwalk', 8, 'Syntax: .cheat waterwalk on/off\r\nAllow to walk on water (self or selected character).');
REPLACE INTO `command` VALUES ('combatstop', 3, 'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.');
REPLACE INTO `command` VALUES ('cometome', 9, 'Syntax: .cometome $parameter\nMake selected creature come to your current location (new position not saved to DB).');
REPLACE INTO `command` VALUES ('commands', 0, 'Syntax: .commands\r\n\r\nDisplay a list of available commands for your account level.');
REPLACE INTO `command` VALUES ('cooldown', 4, 'Syntax: .cooldown [#spell_id]\r\n\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).');
REPLACE INTO `command` VALUES ('damage', 7, 'Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.');
REPLACE INTO `command` VALUES ('debug', 8, 'Syntax: .debug $subcommand\nType .debug to see the list of possible subcommands or .help debug $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('debug anim', 8, 'TODO');
REPLACE INTO `command` VALUES ('debug areatriggers', 8, 'Syntax: .debug areatriggers\nToggle debug mode for areatriggers. In debug mode GM will be notified if reaching an areatrigger');
REPLACE INTO `command` VALUES ('debug arena', 8, 'Syntax: .debug arena\r\n\r\nToggle debug mode for arenas. In debug mode GM can start arena with single player.');
REPLACE INTO `command` VALUES ('debug bg', 8, 'Syntax: .debug bg\r\n\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player.');
REPLACE INTO `command` VALUES ('debug entervehicle', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug getitemstate', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug getitemvalue', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug getvalue', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug hostil', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug itemexpire', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug lootrecipient', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug los', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug Mod32Value', 8, 'Syntax: .debug Mod32Value #field #value\r\n\r\nAdd #value to field #field of your character.');
REPLACE INTO `command` VALUES ('debug moveflags', 8, 'Syntax: .debug moveflags [$newMoveFlags [$newMoveFlags2]]\r\nNo params given will output the current moveflags of the target');
REPLACE INTO `command` VALUES ('debug play', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug play cinematic', 8, 'Syntax: .debug play cinematic #cinematicid\r\n\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.\r\n');
REPLACE INTO `command` VALUES ('debug play movie', 8, 'Syntax: .debug play movie #movieid\r\n\r\nPlay movie #movieid for you.');
REPLACE INTO `command` VALUES ('debug play sound', 8, 'Syntax: .debug play sound #soundid\r\n\r\nPlay sound with #soundid.\r\nSound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...');
REPLACE INTO `command` VALUES ('debug send', 8, '');
REPLACE INTO `command` VALUES ('debug send buyerror', 8, '');
REPLACE INTO `command` VALUES ('debug send channelnotify', 8, '');
REPLACE INTO `command` VALUES ('debug send chatmmessage', 8, '');
REPLACE INTO `command` VALUES ('debug send equiperror', 8, '');
REPLACE INTO `command` VALUES ('debug send largepacket', 8, '');
REPLACE INTO `command` VALUES ('debug send opcode', 8, '');
REPLACE INTO `command` VALUES ('debug send qinvalidmsg', 8, '');
REPLACE INTO `command` VALUES ('debug send qpartymsg', 8, '');
REPLACE INTO `command` VALUES ('debug send sellerror', 8, '');
REPLACE INTO `command` VALUES ('debug send setphaseshift', 8, '');
REPLACE INTO `command` VALUES ('debug send spellfail', 8, '');
REPLACE INTO `command` VALUES ('debug setaurastate', 8, '');
REPLACE INTO `command` VALUES ('debug setbit', 8, '');
REPLACE INTO `command` VALUES ('debug setitemvalue', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug setvalue', 8, '');
REPLACE INTO `command` VALUES ('debug setvid', 8, '');
REPLACE INTO `command` VALUES ('debug spawnvehicle', 8, '');
REPLACE INTO `command` VALUES ('debug threat', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('debug update', 8, '');
REPLACE INTO `command` VALUES ('debug uws', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('demorph', 3, 'Syntax: .demorph\r\n\r\nDemorph the selected player.');
REPLACE INTO `command` VALUES ('deserter bg add', 7, 'Syntax: .deserter bg add $time \n\n Adds the bg deserter debuff to your target with $time duration.');
REPLACE INTO `command` VALUES ('deserter bg remove', 7, 'Syntax: .deserter bg remove \n\n Removes the bg deserter debuff from your target.');
REPLACE INTO `command` VALUES ('deserter instance add', 7, 'Syntax: .deserter instance add $time \n\n Adds the instance deserter debuff to your target with $time duration.');
REPLACE INTO `command` VALUES ('deserter instance remove', 7, 'Syntax: .deserter instance remove \n\n Removes the instance deserter debuff from your target.');
REPLACE INTO `command` VALUES ('dev', 8, 'Syntax: .dev [on/off]\r\n\r\nEnable or Disable in game Dev tag or show current state if on/off not provided.');
REPLACE INTO `command` VALUES ('die', 7, 'Syntax: .die\r\n\r\nKill the selected player. If no player is selected, it will kill you.');
REPLACE INTO `command` VALUES ('disable add battleground', 8, 'Syntax: .disable add battleground $entry $flag $comment');
REPLACE INTO `command` VALUES ('disable add map', 8, 'Syntax: .disable add map $entry $flag $comment');
REPLACE INTO `command` VALUES ('disable add outdoorpvp', 8, 'Syntax: .disable add outdoorpvp $entry $flag $comment');
REPLACE INTO `command` VALUES ('disable add quest', 8, 'Syntax: .disable add quest $entry $flag $comment');
REPLACE INTO `command` VALUES ('disable add spell', 8, 'Syntax: .disable add spell $entry $flag $comment');
REPLACE INTO `command` VALUES ('disable add vmap', 8, 'Syntax: .disable add vmap $entry $flag $comment');
REPLACE INTO `command` VALUES ('disable remove battleground', 8, 'Syntax: .disable remove battleground $entry');
REPLACE INTO `command` VALUES ('disable remove map', 8, 'Syntax: .disable remove map $entry');
REPLACE INTO `command` VALUES ('disable remove outdoorpvp', 8, 'Syntax: .disable remove outdoorpvp $entry');
REPLACE INTO `command` VALUES ('disable remove quest', 8, 'Syntax: .disable remove quest $entry');
REPLACE INTO `command` VALUES ('disable remove spell', 8, 'Syntax: .disable remove spell $entry');
REPLACE INTO `command` VALUES ('disable remove vmap', 8, 'Syntax: .disable remove vmap $entry');
REPLACE INTO `command` VALUES ('dismount', 0, 'Syntax: .dismount\r\n\r\nDismount you, if you are mounted.');
REPLACE INTO `command` VALUES ('distance', 8, 'Syntax: .distance\r\n\r\nDisplay the distance from your character to the selected creature.');
REPLACE INTO `command` VALUES ('event', 6, 'Syntax: .event #event_id\r\nShow details about event with #event_id.');
REPLACE INTO `command` VALUES ('event activelist', 6, 'Syntax: .event activelist\r\nShow list of currently active events.');
REPLACE INTO `command` VALUES ('event start', 6, 'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).');
REPLACE INTO `command` VALUES ('event stop', 6, 'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).');
REPLACE INTO `command` VALUES ('flusharenapoints', 7, 'Syntax: .flusharenapoints\r\n\r\nUse it to distribute arena points based on arena team ratings, and start a new week.');
REPLACE INTO `command` VALUES ('freeze', 3, 'Syntax: .freeze (#player)\r\n"Freezes" #player and disables his chat. When using this without #name it will freeze your target.');
REPLACE INTO `command` VALUES ('gm', 1, 'Syntax: .gm [on/off]\r\n\r\nEnable or Disable in game GM MODE or show current state of on/off not provided.');
REPLACE INTO `command` VALUES ('gm chat', 1, 'Syntax: .gm chat [on/off]\r\n\r\nEnable or disable chat GM MODE (show gm badge in messages) or show current state of on/off not provided.');
REPLACE INTO `command` VALUES ('gm fly', 1, 'Syntax: .gm fly [on/off]\r\nEnable/disable gm fly mode.');
REPLACE INTO `command` VALUES ('gm ingame', 1, 'Syntax: .gm ingame\r\n\r\nDisplay a list of available in game Game Masters.');
REPLACE INTO `command` VALUES ('gm list', 1, 'Syntax: .gm list\r\n\r\nDisplay a list of all Game Masters accounts and security levels.');
REPLACE INTO `command` VALUES ('gm visible', 1, 'Syntax: .gm visible on/off\r\n\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.');
REPLACE INTO `command` VALUES ('gmannounce', 3, 'Syntax: .gmannounce $announcement\r\nSend an announcement to online Gamemasters.');
REPLACE INTO `command` VALUES ('gmnameannounce', 3, 'Syntax: .gmnameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.');
REPLACE INTO `command` VALUES ('gmnotify', 3, 'Syntax: .gmnotify $notification\r\nDisplays a notification on the screen of all online GM\'s.');
REPLACE INTO `command` VALUES ('go', 3, 'Syntax: .go $subcommand\nType .go to see the list of possible subcommands or .help go $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('go creature', 3, 'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.');
REPLACE INTO `command` VALUES ('go gobject', 3, 'Syntax: .go object #gameobject_guid\r\nTeleport your character to gameobject with guid #gameobject_guid');
REPLACE INTO `command` VALUES ('go graveyard', 3, 'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.');
REPLACE INTO `command` VALUES ('go grid', 3, 'Syntax: .go grid #gridX #gridY [#mapId]\r\n\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).');
REPLACE INTO `command` VALUES ('go object', 3, '[DEPRECATED]: use ".go gobject" instead.\r\nSyntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid');
REPLACE INTO `command` VALUES ('go taxinode', 3, 'Syntax: .go taxinode #taxinode\r\n\r\nTeleport player to taxinode coordinates. You can look up zone using .lookup taxinode $namepart');
REPLACE INTO `command` VALUES ('go ticket', 3, 'Syntax: .go ticket #ticketid\r\nTeleports the user to the location where $ticketid was created.');
REPLACE INTO `command` VALUES ('go trigger', 3, 'Syntax: .go trigger #trigger_id\r\n\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.');
REPLACE INTO `command` VALUES ('go xyz', 3, 'Syntax: .go xyz #x #y [#z [#mapid [#orientation]]]\r\n\r\nTeleport player to point with (#x,#y,#z) coordinates at map #mapid with orientation #orientation. If z is not provided, ground/water level will be used. If mapid is not provided, the current map will be used. If #orientation is not provided, the current orientation will be used.');
REPLACE INTO `command` VALUES ('go zonexy', 3, 'Syntax: .go zonexy #x #y [#zone]\r\n\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart');
REPLACE INTO `command` VALUES ('gobject', 5, 'Syntax: .gobject $subcommand\nType .gobject to see the list of possible subcommands or .help gobject $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('gobject activate', 5, 'Syntax: .gobject activate #guid\r\n\r\nActivates an object like a door or a button.');
REPLACE INTO `command` VALUES ('gobject add', 5, 'Syntax: .gobject add #id <spawntimeSecs>\r\n\r\nAdd a game object from game object templates to the world at your current location using the #id.\r\nspawntimesecs sets the spawntime, it is optional.\r\n\r\nNote: this is a copy of .gameobject.');
REPLACE INTO `command` VALUES ('gobject add temp', 5, 'Adds a temporary gameobject that is not saved to DB.');
REPLACE INTO `command` VALUES ('gobject delete', 5, 'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.');
REPLACE INTO `command` VALUES ('gobject info', 5, 'Syntax: .gobject info [$object_entry]\r \r Query Gameobject information for selected gameobject or given entry.');
REPLACE INTO `command` VALUES ('gobject move', 5, 'Syntax: .gobject move #goguid [#x #y #z]\r\n\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).');
REPLACE INTO `command` VALUES ('gobject near', 5, 'Syntax: .gobject near  [#distance]\r\n\r\nOutput gameobjects at distance #distance from player. Output gameobject guids and coordinates sorted by distance from character. If #distance not provided use 10 as default value.');
REPLACE INTO `command` VALUES ('gobject set', 5, 'Syntax: ');
REPLACE INTO `command` VALUES ('gobject set phase', 5, 'Syntax: .gobject set phase #guid #phasemask\r\n\r\nGameobject with DB guid #guid phasemask changed to #phasemask with related world vision update for players. Gameobject state saved to DB and persistent.');
REPLACE INTO `command` VALUES ('gobject set state', 5, 'Syntax: ');
REPLACE INTO `command` VALUES ('gobject target', 5, 'Syntax: .gobject target [#go_id|#go_name_part]\r\n\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.');
REPLACE INTO `command` VALUES ('gobject turn', 5, 'Syntax: .gobject turn #goguid \r\n\r\nSet for gameobject #goguid orientation same as current character orientation.');
REPLACE INTO `command` VALUES ('gps', 3, 'Syntax: .gps [$name|$shift-link]\r\n\r\nDisplay the position information for a selected character or creature (also if player name $name provided then for named player, or if creature/gameobject shift-link provided then pointed creature/gameobject if it loaded). Position information includes X, Y, Z, and orientation, map Id and zone Id');
REPLACE INTO `command` VALUES ('group', 2, 'Syntax: .group $subcommand\nType .group to see the list of possible subcommands or .help group $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('group disband', 2, 'Syntax: .group disband [$characterName]\n\nDisbands the given character\'s group.');
REPLACE INTO `command` VALUES ('group join', 2, 'Syntax: .group join $AnyCharacterNameFromGroup [$CharacterName] \r\nAdds to group of player $AnyCharacterNameFromGroup player $CharacterName (or selected).');
REPLACE INTO `command` VALUES ('group leader', 2, 'Syntax: .group leader [$characterName]\n\nSets the given character as his group\'s leader.');
REPLACE INTO `command` VALUES ('group list', 2, 'Syntax: .group list [$CharacterName] \r\nLists all the members of the group/party the player is in.');
REPLACE INTO `command` VALUES ('group remove', 2, 'Syntax: .group remove [$characterName]\n\nRemoves the given character from his group.');
REPLACE INTO `command` VALUES ('groupsummon', 2, 'Syntax: .groupsummon [$charactername]\r\n\r\nTeleport the given character and his group to you. Teleported only online characters but original selected group member can be offline.');
REPLACE INTO `command` VALUES ('guid', 3, 'Syntax: .guid\r\n\r\nDisplay the GUID for the selected character.');
REPLACE INTO `command` VALUES ('guild', 3, 'Syntax: .guild $subcommand\nType .guild to see the list of possible subcommands or .help guild $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('guild create', 3, 'Syntax: .guild create [$GuildLeaderName] "$GuildName"\r\n\r\nCreate a guild named $GuildName with the player $GuildLeaderName (or selected) as leader.  Guild name must in quotes.');
REPLACE INTO `command` VALUES ('guild delete', 7, 'Syntax: .guild delete "$GuildName"\r\n\r\nDelete guild $GuildName. Guild name must in quotes.');
REPLACE INTO `command` VALUES ('guild info', 3, 'Shows information about the target\'s guild or a given Guild Id or Name.');
REPLACE INTO `command` VALUES ('guild invite', 7, 'Syntax: .guild invite [$CharacterName] "$GuildName"\r\n\r\nAdd player $CharacterName (or selected) into a guild $GuildName. Guild name must in quotes.');
REPLACE INTO `command` VALUES ('guild rank', 7, 'Syntax: .guild rank [$CharacterName] #Rank\r\n\r\nSet for player $CharacterName (or selected) rank #Rank in a guild.');
REPLACE INTO `command` VALUES ('guild uninvite', 7, 'Syntax: .guild uninvite [$CharacterName]\r\n\r\nRemove player $CharacterName (or selected) from a guild.');
REPLACE INTO `command` VALUES ('help', 0, 'Syntax: .help [$command]\r\n\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.');
REPLACE INTO `command` VALUES ('hidearea', 7, 'Syntax: .hidearea #areaid\r\n\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.');
REPLACE INTO `command` VALUES ('honor', 6, 'Syntax: .honor $subcommand\nType .honor to see the list of possible subcommands or .help honor $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('honor add', 6, 'Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained today) to the selected player.');
REPLACE INTO `command` VALUES ('honor add kill', 6, 'Syntax: .honor add kill\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)');
REPLACE INTO `command` VALUES ('honor update', 6, 'Syntax: .honor update\r\n\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.');
REPLACE INTO `command` VALUES ('instance', 7, 'Syntax: .instance $subcommand\nType .instance to see the list of possible subcommands or .help instance $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('instance getbossstate', 7, 'Syntax: .instance getbossstate $bossId [$Name]\r\nGets the current EncounterState for the provided boss id.\r\nIf no character name is provided, the current map will be used as target.');
REPLACE INTO `command` VALUES ('instance listbinds', 7, 'Syntax: .instance listbinds\r\n  Lists the binds of the selected player.');
REPLACE INTO `command` VALUES ('instance savedata', 7, 'Syntax: .instance savedata\r\n  Save the InstanceData for the current player\'s map to the DB.');
REPLACE INTO `command` VALUES ('instance setbossstate', 7, 'Syntax: .instance setbossstate $bossId $encounterState [$Name]\r\nSets the EncounterState for the given boss id to a new value. EncounterStates range from 0 to 5.\r\nIf no character name is provided, the current map will be used as target.');
REPLACE INTO `command` VALUES ('instance unbind', 7, 'Syntax: .instance unbind <mapid|all> [difficulty]\r\n  Clear all/some of player\'s binds');
REPLACE INTO `command` VALUES ('itemmove', 7, 'Syntax: .itemmove #sourceslotid #destinationslotid\r\n\r\nMove an item from slots #sourceslotid to #destinationslotid in your inventory\r\n\r\nNot yet implemented');
REPLACE INTO `command` VALUES ('kick', 4, 'Syntax: .kick [$charactername] [$reason]\r\n\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is "No Reason".');
REPLACE INTO `command` VALUES ('learn', 6, 'Syntax: .learn #spell [all]\r\n\r\nSelected character learn a spell of id #spell. If \'all\' provided then all ranks learned.');
REPLACE INTO `command` VALUES ('learn all', 6, '');
REPLACE INTO `command` VALUES ('learn all crafts', 6, 'Syntax: .learn crafts\r\n\r\nLearn all professions and recipes.');
REPLACE INTO `command` VALUES ('learn all default', 7, 'Syntax: .learn all default [$playername]\r\n\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.');
REPLACE INTO `command` VALUES ('learn all gm', 7, 'Syntax: .learn all gm\r\n\r\nLearn all default spells for Game Masters.');
REPLACE INTO `command` VALUES ('learn all lang', 7, 'Syntax: .learn all lang\r\n\r\nLearn all languages');
REPLACE INTO `command` VALUES ('learn all my', 8, '');
REPLACE INTO `command` VALUES ('learn all my class', 8, 'Syntax: .learn all my class\r\n\r\nLearn all spells and talents available for his class.');
REPLACE INTO `command` VALUES ('learn all my pettalents', 8, 'Syntax: .learn all my pettalents\r\n\r\nLearn all talents for your pet available for his creature type (only for hunter pets).');
REPLACE INTO `command` VALUES ('learn all my spells', 8, 'Syntax: .learn all my spells\r\n\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.');
REPLACE INTO `command` VALUES ('learn all my talents', 8, 'Syntax: .learn all my talents\r\n\r\nLearn all talents (and spells with first rank learned as talent) available for his class.');
REPLACE INTO `command` VALUES ('learn all recipes', 8, 'Syntax: .learn all recipes [$profession]\r\rLearns all recipes of specified profession and sets skill level to max.\rExample: .learn all recipes enchanting');
REPLACE INTO `command` VALUES ('levelup', 6, 'Syntax: .levelup [$playername] [#numberoflevels]\r\n\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.');
REPLACE INTO `command` VALUES ('lfg', 8, '');
REPLACE INTO `command` VALUES ('lfg clean', 8, 'Syntax: .flg clean\n Cleans current queue, only for debugging purposes.');
REPLACE INTO `command` VALUES ('lfg group', 8, 'Syntax: .lfg group\n Shows information about all players in the group  (state, roles, comment, dungeons selected).');
REPLACE INTO `command` VALUES ('lfg options', 8, 'Syntax: .lfg options [new value]\n Shows current lfg options. New value is set if extra param is present.');
REPLACE INTO `command` VALUES ('lfg player', 8, 'Syntax: .lfg player\n Shows information about player (state, roles, comment, dungeons selected).');
REPLACE INTO `command` VALUES ('lfg queue', 8, 'Syntax: .lfg queue\n Shows info about current lfg queues.');
REPLACE INTO `command` VALUES ('linkgrave', 9, 'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\n\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).');
REPLACE INTO `command` VALUES ('list', 3, 'Syntax: .list $subcommand\nType .list to see the list of possible subcommands or .help list $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('list auras', 3, 'Syntax: .list auras\nList auras (passive and active) of selected creature or player. If no creature or player is selected, list your own auras.');
REPLACE INTO `command` VALUES ('list creature', 3, 'Syntax: .list creature #creature_id [#max_count]\r\n\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.');
REPLACE INTO `command` VALUES ('list gobject', 3, 'Syntax: .list object #gameobject_id [#max_count]\r\n\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.');
REPLACE INTO `command` VALUES ('list item', 3, 'Syntax: .list item #item_id [#max_count]\r\n\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.');
REPLACE INTO `command` VALUES ('list object', 3, '[DEPRECATED]: use ".list gobject" instead.\r\nSyntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid');
REPLACE INTO `command` VALUES ('lookup', 5, 'Syntax: .lookup $subcommand\nType .lookup to see the list of possible subcommands or .help lookup $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('lookup area', 5, 'Syntax: .lookup area $namepart\r\n\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.');
REPLACE INTO `command` VALUES ('lookup creature', 5, 'Syntax: .lookup creature $namepart\r\n\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.');
REPLACE INTO `command` VALUES ('lookup event', 5, 'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.');
REPLACE INTO `command` VALUES ('lookup faction', 5, 'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.');
REPLACE INTO `command` VALUES ('lookup gobject', 5, 'Syntax: .lookup object $objname\r\n\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.');
REPLACE INTO `command` VALUES ('lookup item', 6, 'Syntax: .lookup item $itemname\r\n\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.');
REPLACE INTO `command` VALUES ('lookup itemset', 6, 'Syntax: .lookup itemset $itemname\r\n\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.');
REPLACE INTO `command` VALUES ('lookup map', 5, 'Syntax: .lookup map $namepart\r\n\r\nLooks up a map by $namepart, and returns all matches with their map ID\'s.');
REPLACE INTO `command` VALUES ('lookup object', 5, '[DEPRECATED]: use ".lookup gobject" instead.\r\nSyntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid');
REPLACE INTO `command` VALUES ('lookup player', 4, '');
REPLACE INTO `command` VALUES ('lookup player account', 4, 'Syntax: .lookup player account $account ($limit) \r\n\r\n Searchs players, which account username is $account with optional parametr $limit of results.');
REPLACE INTO `command` VALUES ('lookup player email', 4, 'Syntax: .lookup player email $email ($limit) \r\n\r\n Searchs players, which account email is $email with optional parametr $limit of results.');
REPLACE INTO `command` VALUES ('lookup player ip', 4, 'Syntax: .lookup player ip $ip ($limit) \r\n\r\n Searchs players, which account ast_ip is $ip with optional parametr $limit of results.');
REPLACE INTO `command` VALUES ('lookup quest', 7, 'Syntax: .lookup quest $namepart\r\n\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.');
REPLACE INTO `command` VALUES ('lookup skill', 7, 'Syntax: .lookup skill $$namepart\r\n\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.');
REPLACE INTO `command` VALUES ('lookup spell', 7, 'Syntax: .lookup spell $namepart\r\n\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.');
REPLACE INTO `command` VALUES ('lookup spell id', 7, 'Syntax: .lookup spell id #spellid\n\nLooks up a spell by #spellid, and returns the match with its spell name.');
REPLACE INTO `command` VALUES ('lookup taxinode', 7, 'Syntax: .lookup taxinode $substring\r\n\r\nSearch and output all taxinodes with provide $substring in name.');
REPLACE INTO `command` VALUES ('lookup tele', 1, 'Syntax: .lookup tele $substring\r\n\r\nSearch and output all .tele command locations with provide $substring in name.');
REPLACE INTO `command` VALUES ('lookup title', 4, 'Syntax: .lookup title $$namepart\r\n\r\nLooks up a title by $namepart, and returns all matches with their title ID\'s and index\'s.');
REPLACE INTO `command` VALUES ('mailbox', 1, 'Syntax: .mailbox\r\n\r\nShow your mailbox content.');
REPLACE INTO `command` VALUES ('maxskill', 3, 'Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum values for its current level.');
REPLACE INTO `command` VALUES ('mmap', 8, 'Syntax: Syntax: .mmaps $subcommand Type .mmaps to see the list of possible subcommands or .help mmaps $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('mmap loadedtiles', 8, 'Syntax: .mmap loadedtiles to show which tiles are currently loaded');
REPLACE INTO `command` VALUES ('mmap loc', 8, 'Syntax: .mmap loc to print on which tile one is');
REPLACE INTO `command` VALUES ('mmap path', 8, 'Syntax: .mmap path to calculate and show a path to current select unit');
REPLACE INTO `command` VALUES ('mmap stats', 8, 'Syntax: .mmap stats to show information about current state of mmaps');
REPLACE INTO `command` VALUES ('mmap testarea', 8, 'Syntax: .mmap testarea to calculate paths for all nearby npcs to player');
REPLACE INTO `command` VALUES ('modify', 6, 'Syntax: .modify $subcommand\nType .modify to see the list of possible subcommands or .help modify $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('modify arenapoints', 7, 'Syntax: .modify arenapoints #value\r\nAdd $amount arena points to the selected player.');
REPLACE INTO `command` VALUES ('modify bit', 7, 'Syntax: .modify bit #field #bit\r\n\r\nToggle the #bit bit of the #field field for the selected player. If no player is selected, modify your character.');
REPLACE INTO `command` VALUES ('modify drunk', 7, 'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.');
REPLACE INTO `command` VALUES ('modify energy', 7, 'Syntax: .modify energy #energy\r\n\r\nModify the energy of the selected player. If no player is selected, modify your energy.');
REPLACE INTO `command` VALUES ('modify faction', 7, 'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\n\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.');
REPLACE INTO `command` VALUES ('modify gender', 7, 'Syntax: .modify gender male/female\r\n\r\nChange gender of selected player.');
REPLACE INTO `command` VALUES ('modify honor', 6, 'Syntax: .modify honor $amount\r\n\r\nAdd $amount honor points to the selected player.');
REPLACE INTO `command` VALUES ('modify hp', 6, 'Syntax: .modify hp #newhp\r\n\r\nModify the hp of the selected player. If no player is selected, modify your hp.');
REPLACE INTO `command` VALUES ('modify mana', 6, 'Syntax: .modify mana #newmana\r\n\r\nModify the mana of the selected player. If no player is selected, modify your mana.');
REPLACE INTO `command` VALUES ('modify money', 6, 'Syntax: .modify money #money\r\n.money #money\r\n\r\nAdd or remove money to the selected player. If no player is selected, modify your money.\r\n\r\n #gold can be negative to remove money.');
REPLACE INTO `command` VALUES ('modify mount', 6, 'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.');
REPLACE INTO `command` VALUES ('modify phase', 8, 'Syntax: .modify phase #phasemask\r\n\r\nSelected character phasemask changed to #phasemask with related world vision update. Change active until in game phase changed, or GM-mode enable/disable, or re-login. Character pts pasemask update to same value.');
REPLACE INTO `command` VALUES ('modify rage', 6, 'Syntax: .modify rage #newrage\r\n\r\nModify the rage of the selected player. If no player is selected, modify your rage.');
REPLACE INTO `command` VALUES ('modify reputation', 6, 'Syntax: .modify reputation #repId (#repvalue | $rankname [#delta])\nSets the selected players reputation with faction #repId to #repvalue or to $reprank.\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.');
REPLACE INTO `command` VALUES ('modify runicpower', 6, 'Syntax: .modify runicpower #newrunicpower\r\n\r\nModify the runic power of the selected player. If no player is selected, modify your runic power.');
REPLACE INTO `command` VALUES ('modify scale', 4, '.modify scale #scale\nModify size of the selected player or creature to "normal scale"*rate. If no player or creature is selected, modify your size.\n#rate may range from 0.1 to 10.');
REPLACE INTO `command` VALUES ('modify speed', 1, 'Syntax: .modify speed $speedtype #rate\r\n\r\nModify the running speed of the selected player to "normal base run speed"= 1. If no player is selected, modify your speed.\r\n\r\n$speedtypes may be fly, all, walk, backwalk, or swim.\r\n\r\n #rate may range from 0.1 to 50.');
REPLACE INTO `command` VALUES ('modify speed all', 6, 'Syntax: .modify aspeed #rate\r\n\r\nModify all speeds -run,swim,run back,swim back- of the selected player to "normalbase speed for this move type"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
REPLACE INTO `command` VALUES ('modify speed backwalk', 6, 'Syntax: .modify speed backwalk #rate\r\n\r\nModify the speed of the selected player while running backwards to "normal walk back speed"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
REPLACE INTO `command` VALUES ('modify speed fly', 1, '.modify speed fly #rate\nModify the flying speed of the selected player to "normal flying speed"*rate. If no player is selected, modify your speed.\n #rate may range from 0.1 to 50.');
REPLACE INTO `command` VALUES ('modify speed swim', 1, 'Syntax: .modify speed swim #rate\r\n\r\nModify the swim speed of the selected player to "normal swim speed"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
REPLACE INTO `command` VALUES ('modify speed walk', 1, 'Syntax: .modify speed bwalk #rate\r\n\r\nModify the speed of the selected player while running to "normal walk speed"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
REPLACE INTO `command` VALUES ('modify spell', 9, 'TODO');
REPLACE INTO `command` VALUES ('modify standstate', 7, 'Syntax: .modify standstate #emoteid\r\n\r\nChange the emote of your character while standing to #emoteid.');
REPLACE INTO `command` VALUES ('modify talentpoints', 7, 'Syntax: .modify talentpoints #amount\r\n\r\nSet free talent points for selected character or character\'s pet. It will be reset to default expected at next levelup/login/quest reward.');
REPLACE INTO `command` VALUES ('morph', 3, 'Syntax: .morph #displayid\r\n\r\nChange your current model id to #displayid.');
REPLACE INTO `command` VALUES ('movegens', 8, 'Syntax: .movegens\r\n  Show movement generators stack for selected creature or player.');
REPLACE INTO `command` VALUES ('mute', 3, 'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\n\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.');
REPLACE INTO `command` VALUES ('mutehistory', 3, 'Syntax: .mutehistory $accountName. Shows mute history for an account.');
REPLACE INTO `command` VALUES ('nameannounce', 4, 'Syntax: .nameannounce $announcement.\nSend an announcement to all online players, displaying the name of the sender.');
REPLACE INTO `command` VALUES ('neargrave', 3, 'Syntax: .neargrave [alliance|horde]\r\n\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).');
REPLACE INTO `command` VALUES ('notify', 4, 'Syntax: .notify $MessageToBroadcast\r\n\r\nSend a global message to all players online in screen.');
REPLACE INTO `command` VALUES ('npc', 5, 'Syntax: .npc $subcommand\nType .npc to see the list of possible subcommands or .help npc $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('npc add', 5, 'Syntax: .npc add #creatureid\r\n\r\nSpawn a creature by the given template id of #creatureid.');
REPLACE INTO `command` VALUES ('npc add formation', 8, 'Syntax: .npc add formation $leader\nAdd selected creature to a leader\'s formation.');
REPLACE INTO `command` VALUES ('npc add item', 7, 'Syntax: .npc add item #itemId <#maxcount><#incrtime><#extendedcost>r\r\n\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.');
REPLACE INTO `command` VALUES ('npc add move', 5, 'Syntax: .npc add move #creature_guid [#waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.');
REPLACE INTO `command` VALUES ('npc add temp', 8, 'Syntax: .npc add temp\r\n\r\nAdds temporary NPC, not saved to database.');
REPLACE INTO `command` VALUES ('npc delete', 7, 'Syntax: .npc delete [#guid]\r\n\r\nDelete creature with guid #guid (or the selected if no guid is provided)');
REPLACE INTO `command` VALUES ('npc delete item', 7, 'Syntax: .npc delete item #itemId\r\n\r\nRemove item #itemid from item list of selected vendor.');
REPLACE INTO `command` VALUES ('npc follow', 7, 'Syntax: .npc follow start\r\n\r\nSelected creature start follow you until death/fight/etc.');
REPLACE INTO `command` VALUES ('npc follow stop', 7, 'Syntax: .npc follow stop\r\n\r\nSelected creature (non pet) stop follow you.');
REPLACE INTO `command` VALUES ('npc info', 5, 'Syntax: .npc info\r\n\r\nDisplay a list of details for the selected creature.\r\n\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n\r\n- Field flags, dynamic flags, faction template, \r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.');
REPLACE INTO `command` VALUES ('npc move', 5, 'Syntax: .npc move [#creature_guid]\r\n\r\nMove the targeted creature spawn point to your coordinates.');
REPLACE INTO `command` VALUES ('npc near', 5, 'Syntax: ');
REPLACE INTO `command` VALUES ('npc playemote', 5, 'Syntax: .npc playemote #emoteid\r\n\r\nMake the selected creature emote with an emote of id #emoteid.');
REPLACE INTO `command` VALUES ('npc say', 7, 'Syntax: .npc say $message\nMake selected creature say specified message.');
REPLACE INTO `command` VALUES ('npc set', 7, 'Syntax: ');
REPLACE INTO `command` VALUES ('npc set allowmove', 7, 'Syntax: .npc set allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented.');
REPLACE INTO `command` VALUES ('npc set data', 7, 'Syntax: .npc set data $field $data\nSets data for the selected creature. Used for testing Scripting');
REPLACE INTO `command` VALUES ('npc set entry', 7, 'Syntax: .npc set entry $entry\nSwitch selected creature with another entry from creature_template. - New creature.id value not saved to DB.');
REPLACE INTO `command` VALUES ('npc set faction original', 7, 'Syntax: .npc set faction original\r\n\r\nRevert the temporal faction of the selected creature.');
REPLACE INTO `command` VALUES ('npc set faction permanent', 7, 'Syntax: .npc set faction permanent #factionid\r\n\r\nPermanently set the faction of the selected creature to #factionid.');
REPLACE INTO `command` VALUES ('npc set faction temp', 7, 'Syntax: .npc set faction temp #factionid\r\n\r\nTemporarily set the faction of the selected creature to #factionid.');
REPLACE INTO `command` VALUES ('npc set flag', 7, 'Syntax: .npc set flag #npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.');
REPLACE INTO `command` VALUES ('npc set level', 7, 'Syntax: .npc set level #level\r\n\r\nChange the level of the selected creature to #level.\r\n\r\n#level may range from 1 to (CONFIG_MAX_PLAYER_LEVEL) + 3.');
REPLACE INTO `command` VALUES ('npc set link', 7, 'Syntax: .npc set link $creatureGUID\r\n\r\nLinks respawn of selected creature to the condition that $creatureGUID defined is alive.');
REPLACE INTO `command` VALUES ('npc set model', 7, 'Syntax: .npc set model #displayid\r\n\r\nChange the model id of the selected creature to #displayid.');
REPLACE INTO `command` VALUES ('npc set movetype', 7, 'Syntax: .npc set movetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.');
REPLACE INTO `command` VALUES ('npc set phase', 7, 'Syntax: .npc set phase #phasemask\r\n\r\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable..');
REPLACE INTO `command` VALUES ('npc set spawndist', 7, 'Syntax: .npc set spawndist #dist\r\n\r\nAdjust spawndistance of selected creature to dist.');
REPLACE INTO `command` VALUES ('npc set spawntime', 7, 'Syntax: .npc set spawntime #time \r\n\r\nAdjust spawntime of selected creature to time.');
REPLACE INTO `command` VALUES ('npc tame', 5, 'Syntax: ');
REPLACE INTO `command` VALUES ('npc textemote', 7, 'Syntax: .npc textemote #emoteid\r\n\r\nMake the selected creature to do textemote with an emote of id #emoteid.');
REPLACE INTO `command` VALUES ('npc whisper', 7, 'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.');
REPLACE INTO `command` VALUES ('npc yell', 7, 'Syntax: .npc yell $message\nMake selected creature yell specified message.');
REPLACE INTO `command` VALUES ('pdump', 8, 'Syntax: .pdump $subcommand\nType .pdump to see the list of possible subcommands or .help pdump $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('pdump load', 8, 'Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLoad character dump from dump file into character list of $account with saved or $newname, with saved (or first free) or $newguid guid.');
REPLACE INTO `command` VALUES ('pdump write', 8, 'Syntax: .pdump write $filename $playerNameOrGUID\r\nWrite character dump with name/guid $playerNameOrGUID to file $filename.');
REPLACE INTO `command` VALUES ('pet', 8, 'Syntax: .pet $subcommand\nType .pet to see the list of possible subcommands or .help pet $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('pet create', 8, 'Syntax: .pet create\r\n\r\nCreates a pet of the selected creature.');
REPLACE INTO `command` VALUES ('pet learn', 8, 'Syntax: .pet learn\r\n\r\nLearn #spellid to pet.');
REPLACE INTO `command` VALUES ('pet unlearn', 8, 'Syntax: .pet unlean\r\n\r\nunLearn #spellid to pet.');
REPLACE INTO `command` VALUES ('pinfo', 1, 'Syntax: .pinfo [$player_name/#GUID]\r\n\r\nOutput account information and guild information for selected player or player find by $player_name or #GUID.');
REPLACE INTO `command` VALUES ('playall', 8, 'Syntax: .playall #soundid\r\n\r\nPlayer a sound to whole server.');
REPLACE INTO `command` VALUES ('player learn', 8, 'Syntax: .player learn #playername #spell [all].');
REPLACE INTO `command` VALUES ('player unlearn', 8, 'Syntax: .player unlearn #playername #spell [all].');
REPLACE INTO `command` VALUES ('possess', 8, 'Syntax: .possess\r\n\r\nPossesses indefinitely the selected creature.');
REPLACE INTO `command` VALUES ('quest', 7, 'Syntax: .quest $subcommand\nType .quest to see the list of possible subcommands or .help quest $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('quest add', 7, 'Syntax: .quest add #quest_id\r\n\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.');
REPLACE INTO `command` VALUES ('quest complete', 7, 'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.');
REPLACE INTO `command` VALUES ('quest remove', 7, 'Syntax: .quest remove #quest_id\r\n\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.');
REPLACE INTO `command` VALUES ('quest reward', 7, 'Syntax: .quest reward #questId\n\nGrants quest reward to selected player and removes quest from his log (quest must be in completed state).');
REPLACE INTO `command` VALUES ('recall', 1, 'Syntax: .recall [$playername]\r\n\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you.');
REPLACE INTO `command` VALUES ('reload', 8, 'Syntax: .reload $subcommand\nType .reload to see the list of possible subcommands or .help reload $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('reload access_requirement', 8, 'Syntax: .reload access_requirement\nReload access_requirement table.');
REPLACE INTO `command` VALUES ('reload achievement_criteria_data', 8, 'Syntax: .reload achievement_criteria_data\nReload achievement_criteria_data table.');
REPLACE INTO `command` VALUES ('reload achievement_reward', 8, 'Syntax: .reload achievement_reward\nReload achievement_reward table.');
REPLACE INTO `command` VALUES ('reload achievement_reward_locale', 8, 'Syntax: .reload achievement_reward_locale\nReload achievement_reward_locale table.');
REPLACE INTO `command` VALUES ('reload acore_string', 8, 'Syntax: .reload acore_string\nReload acore_string table.');
REPLACE INTO `command` VALUES ('reload all', 8, 'Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded.');
REPLACE INTO `command` VALUES ('reload all achievement', 8, 'Syntax: .reload all achievement\r\n\r\nReload achievement_reward, achievement_criteria_data tables.');
REPLACE INTO `command` VALUES ('reload all area', 8, 'Syntax: .reload all area\r\n\r\nReload areatrigger_teleport, areatrigger_tavern, game_graveyard_zone tables.');
REPLACE INTO `command` VALUES ('reload all gossips', 8, 'Syntax: .reload all gossips\nReload gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables.');
REPLACE INTO `command` VALUES ('reload all item', 8, 'Syntax: .reload all item\nReload page_text, item_enchantment_table tables.');
REPLACE INTO `command` VALUES ('reload all locales', 8, 'Syntax: .reload all locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.');
REPLACE INTO `command` VALUES ('reload all loot', 8, 'Syntax: .reload all loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.');
REPLACE INTO `command` VALUES ('reload all npc', 8, 'Syntax: .reload all npc\nReload npc_option, npc_trainer, npc vendor, points of interest tables.');
REPLACE INTO `command` VALUES ('reload all quest', 8, 'Syntax: .reload all quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.');
REPLACE INTO `command` VALUES ('reload all scripts', 8, 'Syntax: .reload all scripts\nReload gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables.');
REPLACE INTO `command` VALUES ('reload all spell', 8, 'Syntax: .reload all spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.');
REPLACE INTO `command` VALUES ('reload areatrigger_involvedrelation', 8, 'Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table.');
REPLACE INTO `command` VALUES ('reload areatrigger_tavern', 8, 'Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table.');
REPLACE INTO `command` VALUES ('reload areatrigger_teleport', 8, 'Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table.');
REPLACE INTO `command` VALUES ('reload auctions', 8, 'Syntax: .reload auctions\nReload dynamic data tables from the database.');
REPLACE INTO `command` VALUES ('reload autobroadcast', 8, 'Syntax: .reload autobroadcast\nReload autobroadcast table.');
REPLACE INTO `command` VALUES ('reload battleground_template', 8, 'Syntax: .reload battleground_template\r\nReload Battleground Templates.');
REPLACE INTO `command` VALUES ('reload broadcast_text', 8, 'Syntax: .reload broadcast_text\r\n\r\nReload broadcast_text table.');
REPLACE INTO `command` VALUES ('reload command', 8, 'Syntax: .reload command\nReload command table.');
REPLACE INTO `command` VALUES ('reload conditions', 8, 'Reload conditions table.');
REPLACE INTO `command` VALUES ('reload config', 8, 'Syntax: .reload config\r\n\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.');
REPLACE INTO `command` VALUES ('reload creature_linked_respawn', 8, 'Syntax: .reload creature_linked_respawn\r\nReload creature_linked_respawn table.');
REPLACE INTO `command` VALUES ('reload creature_loot_template', 8, 'Syntax: .reload creature_loot_template\nReload creature_loot_template table.');
REPLACE INTO `command` VALUES ('reload creature_onkill_reputation', 8, 'Syntax: .reload creature_onkill_reputation\r\nReload creature_onkill_reputation table.');
REPLACE INTO `command` VALUES ('reload creature_questender', 8, 'Syntax: .reload creature_questender\nReload creature_questender table.');
REPLACE INTO `command` VALUES ('reload creature_queststarter', 8, 'Syntax: .reload creature_queststarter\nReload creature_queststarter table.');
REPLACE INTO `command` VALUES ('reload creature_template', 8, 'Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template.');
REPLACE INTO `command` VALUES ('reload creature_template_locale', 8, 'Syntax: .reload creature_template_locale\nReload creature_template_locale table.');
REPLACE INTO `command` VALUES ('reload creature_text', 8, 'Syntax: .reload creature_text\r\nReload creature_text table.');
REPLACE INTO `command` VALUES ('reload creature_text_locale', 8, 'Syntax: .reload creature_text_locale\nReload creature_text_locale Table.');
REPLACE INTO `command` VALUES ('reload disables', 8, 'Syntax: .reload disables\r\nReload disables table.');
REPLACE INTO `command` VALUES ('reload disenchant_loot_template', 8, 'Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table.');
REPLACE INTO `command` VALUES ('reload event_scripts', 8, 'Syntax: .reload event_scripts\nReload event_scripts table.');
REPLACE INTO `command` VALUES ('reload fishing_loot_template', 8, 'Syntax: .reload fishing_loot_template\nReload fishing_loot_template table.');
REPLACE INTO `command` VALUES ('reload gameobject_loot_template', 8, 'Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table.');
REPLACE INTO `command` VALUES ('reload gameobject_questender', 8, 'Syntax: .reload gameobject_questender\\nReload gameobject_questender table.');
REPLACE INTO `command` VALUES ('reload gameobject_queststarter', 8, 'Syntax: .reload gameobject_queststarter\nReload gameobject_queststarter table.');
REPLACE INTO `command` VALUES ('reload gameobject_template_locale', 8, 'Syntax: .reload gameobject_template_locale\nReload gameobject_template_locale table.');
REPLACE INTO `command` VALUES ('reload game_graveyard', 8, 'Syntax: .reload game_graveyard\nReload game_graveyard table.');
REPLACE INTO `command` VALUES ('reload game_tele', 8, 'Syntax: .reload game_tele\nReload game_tele table.');
REPLACE INTO `command` VALUES ('reload gm_tickets', 8, 'Syntax: .reload gm_tickets\nReload gm_tickets table.');
REPLACE INTO `command` VALUES ('reload gossip_menu', 8, 'Syntax: .reload gossip_menu\nReload gossip_menu table.');
REPLACE INTO `command` VALUES ('reload gossip_menu_option', 8, 'Syntax: .reload gossip_menu_option\nReload gossip_menu_option table.');
REPLACE INTO `command` VALUES ('reload gossip_menu_option_locale', 8, 'Syntax: .reload gossip_menu_option_locale\nReload gossip_menu_option_locale table.');
REPLACE INTO `command` VALUES ('reload graveyard_zone', 8, 'Syntax: .reload graveyard_zone');
REPLACE INTO `command` VALUES ('reload item_enchantment_template', 8, 'Syntax: .reload item_enchantment_template\nReload item_enchantment_template table.');
REPLACE INTO `command` VALUES ('reload item_loot_template', 8, 'Syntax: .reload item_loot_template\nReload item_loot_template table.');
REPLACE INTO `command` VALUES ('reload item_set_names', 8, 'Syntax: .reload item_set_names\nReload item_set_names table.');
REPLACE INTO `command` VALUES ('reload item_set_name_locale', 8, 'Syntax: .reload item_set_name_locale\nReload item_set_name_locale table.');
REPLACE INTO `command` VALUES ('reload item_template_locale', 8, 'Syntax: .reload item_template_locale\nReload item_template_locale table.');
REPLACE INTO `command` VALUES ('reload lfg_dungeon_rewards', 8, 'Syntax: .reload lfg_dungeon_rewards\nReload lfg_dungeon_rewards table.');
REPLACE INTO `command` VALUES ('reload mail_level_reward', 8, 'Syntax: .reload mail_level_reward\nReload mail_level_reward table.');
REPLACE INTO `command` VALUES ('reload mail_loot_template', 8, 'Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table.');
REPLACE INTO `command` VALUES ('reload milling_loot_template', 8, 'Syntax: .reload milling_loot_template\nReload milling_loot_template table.');
REPLACE INTO `command` VALUES ('reload npc_spellclick_spells', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('reload npc_text_locale', 8, 'Syntax: .reload npc_text_locale\nReload npc_text_locale table.');
REPLACE INTO `command` VALUES ('reload npc_trainer', 8, 'Syntax: .reload npc_trainer\nReload npc_trainer table.');
REPLACE INTO `command` VALUES ('reload npc_vendor', 8, 'Syntax: .reload npc_vendor\nReload npc_vendor table.');
REPLACE INTO `command` VALUES ('reload page_text', 8, 'Syntax: .reload page_text\nReload page_text table.');
REPLACE INTO `command` VALUES ('reload page_text_locale', 8, 'Syntax: .reload page_text_locale\nReload page_tex_locale table.');
REPLACE INTO `command` VALUES ('reload pickpocketing_loot_template', 8, 'Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table.');
REPLACE INTO `command` VALUES ('reload points_of_interest', 8, 'Syntax: .reload points_of_interest\nReload points_of_interest table.');
REPLACE INTO `command` VALUES ('reload points_of_interest_locale', 8, 'Syntax: .reload points_of_interest_locale\nReload points_of_interest_locale table.');
REPLACE INTO `command` VALUES ('reload prospecting_loot_template', 8, 'Syntax: .reload prospecting_loot_template\nReload prospecting_loot_template table.');
REPLACE INTO `command` VALUES ('reload quest_poi', 8, 'Syntax: .reload quest_poi\nReload quest_poi table.');
REPLACE INTO `command` VALUES ('reload quest_template', 8, 'Syntax: .reload quest_template\nReload quest_template table.');
REPLACE INTO `command` VALUES ('reload quest_template_locale', 8, 'Syntax: .reload quest_template_locale\nReload quest_template_locale table.');
REPLACE INTO `command` VALUES ('reload reference_loot_template', 8, 'Syntax: .reload reference_loot_template\nReload reference_loot_template table.');
REPLACE INTO `command` VALUES ('reload reserved_name', 8, 'Syntax: .reload reserved_name\nReload reserved_name table.');
REPLACE INTO `command` VALUES ('reload skill_discovery_template', 8, 'Syntax: .reload skill_discovery_template\nReload skill_discovery_template table.');
REPLACE INTO `command` VALUES ('reload skill_extra_item_template', 8, 'Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table.');
REPLACE INTO `command` VALUES ('reload skill_fishing_base_level', 8, 'Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table.');
REPLACE INTO `command` VALUES ('reload skinning_loot_template', 8, 'Syntax: .reload skinning_loot_template\nReload skinning_loot_template table.');
REPLACE INTO `command` VALUES ('reload smart_scripts', 8, 'Syntax: .reload smart_scripts\nReload smart_scripts table.');
REPLACE INTO `command` VALUES ('reload spell_area', 8, 'Syntax: .reload spell_area\nReload spell_area table.');
REPLACE INTO `command` VALUES ('reload spell_bonus_data', 8, 'Syntax: .reload spell_bonus_data\nReload spell_bonus_data table.');
REPLACE INTO `command` VALUES ('reload spell_group', 8, 'Syntax: .reload spell_group\nReload spell_group table.');
REPLACE INTO `command` VALUES ('reload spell_group_stack_rules', 8, 'Syntax: .reload spell_group\nReload spell_group_stack_rules table.');
REPLACE INTO `command` VALUES ('reload spell_linked_spell', 8, 'Usage: .reload spell_linked_spell\r\nReloads the spell_linked_spell DB table.');
REPLACE INTO `command` VALUES ('reload spell_loot_template', 8, 'Syntax: .reload spell_loot_template\nReload spell_loot_template table.');
REPLACE INTO `command` VALUES ('reload spell_pet_auras', 8, 'Syntax: .reload spell_pet_auras\nReload spell_pet_auras table.');
REPLACE INTO `command` VALUES ('reload spell_proc', 8, 'Syntax: .reload spell_proc\nReload spell_proc table.');
REPLACE INTO `command` VALUES ('reload spell_proc_event', 8, 'Syntax: .reload spell_proc_event\nReload spell_proc_event table.');
REPLACE INTO `command` VALUES ('reload spell_required', 8, 'Syntax: .reload spell_required\nReload spell_required table.');
REPLACE INTO `command` VALUES ('reload spell_scripts', 8, 'Syntax: .reload spell_scripts\nReload spell_scripts table.');
REPLACE INTO `command` VALUES ('reload spell_target_position', 8, 'Syntax: .reload spell_target_position\nReload spell_target_position table.');
REPLACE INTO `command` VALUES ('reload spell_threats', 8, 'Syntax: .reload spell_threats\nReload spell_threats table.');
REPLACE INTO `command` VALUES ('reload vehicle_accessory', 8, 'Syntax: .reload vehicle_accessory\n\nReloads GUID-based vehicle accessory definitions from the database.');
REPLACE INTO `command` VALUES ('reload vehicle_template_accessory', 8, 'Syntax: .reload vehicle_template_accessory\n\nReloads entry-based vehicle accessory definitions from the database.');
REPLACE INTO `command` VALUES ('reload waypoint_data', 8, 'Syntax: .reload waypoint_data will reload waypoint_data table.');
REPLACE INTO `command` VALUES ('reload waypoint_scripts', 8, 'Syntax: .reload waypoint_scripts\nReload waypoint_scripts table.');
REPLACE INTO `command` VALUES ('repairitems', 2, 'Syntax: .repairitems\r\n\r\nRepair all selected player\'s items.');
REPLACE INTO `command` VALUES ('reset', 7, 'Syntax: .reset $subcommand\nType .reset to see the list of possible subcommands or .help reset $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('reset achievements', 7, 'Syntax: .reset achievements [$playername]\r\n\r\nReset achievements data for selected or named (online or offline) character. Achievements for persistance progress data like completed quests/etc re-filled at reset. Achievements for events like kills/casts/etc will lost.');
REPLACE INTO `command` VALUES ('reset all', 7, 'Syntax: .reset all spells\r\n\r\nSyntax: .reset all talents\r\n\r\nRequest reset spells or talents (including talents for all character\'s pets if any) at next login each existed character.');
REPLACE INTO `command` VALUES ('reset honor', 7, 'Syntax: .reset honor [Playername]\r\n  Reset all honor data for targeted character.');
REPLACE INTO `command` VALUES ('reset level', 7, 'Syntax: .reset level [Playername]\r\n  Reset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.');
REPLACE INTO `command` VALUES ('reset spells', 7, 'Syntax: .reset spells [Playername]\r\n  Removes all non-original spells from spellbook.\r\n. Playername can be name of offline character.');
REPLACE INTO `command` VALUES ('reset stats', 7, 'Syntax: .reset stats [Playername]\r\n  Resets(recalculate) all stats of the targeted player to their original VALUESat current level.');
REPLACE INTO `command` VALUES ('reset talents', 7, 'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player or pet or named player. Playername can be name of offline character. With player talents also will be reset talents for all character\'s pets if any.');
REPLACE INTO `command` VALUES ('respawn', 4, 'Syntax: .respawn\r\n\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.');
REPLACE INTO `command` VALUES ('revive', 4, 'Syntax: .revive\r\n\r\nRevive the selected player. If no player is selected, it will revive you.');
REPLACE INTO `command` VALUES ('save', 0, 'Syntax: .save\r\n\r\nSaves your character.');
REPLACE INTO `command` VALUES ('saveall', 1, 'Syntax: .saveall\r\n\r\nSave all characters in game.');
REPLACE INTO `command` VALUES ('send', 8, 'Syntax: send $subcommand\n Type .send to see a list of possible subcommands\n or .help send $subcommand to see info on the subcommand.');
REPLACE INTO `command` VALUES ('send items', 8, 'Syntax: .send items #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to a player. Subject and mail text must be in "". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.');
REPLACE INTO `command` VALUES ('send mail', 8, 'Syntax: .send mail #playername "#subject" "#text"\r\n\r\nSend a mail to a player. Subject and mail text must be in "".');
REPLACE INTO `command` VALUES ('send message', 8, 'Syntax: .send message $playername $message\r\n\r\nSend screen message to player from ADMINISTRATOR.');
REPLACE INTO `command` VALUES ('send money', 8, 'Syntax: .send money #playername "#subject" "#text" #money\r\n\r\nSend mail with money to a player. Subject and mail text must be in "".');
REPLACE INTO `command` VALUES ('server', 8, 'Syntax: .server $subcommand\nType .server to see the list of possible subcommands or .help server $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('server corpses', 8, 'Syntax: .server corpses\r\n\r\nTriggering corpses expire check in world.');
REPLACE INTO `command` VALUES ('server exit', 8, 'Syntax: .server exit\r\n\r\nTerminate trinity-core NOW. Exit code 0.');
REPLACE INTO `command` VALUES ('server idlerestart', 8, 'Syntax: .server idlerestart #delay\r\n\r\nRestart the server after #delay seconds if no active connections are present (no players). Use #exist_code or 2 as program exist code.');
REPLACE INTO `command` VALUES ('server idlerestart cancel', 8, 'Syntax: .server idlerestart cancel\r\n\r\nCancel the restart/shutdown timer if any.');
REPLACE INTO `command` VALUES ('server idleshutdown', 8, 'Syntax: .server idleshutdown #delay [#exist_code]\r\n\r\nShut the server down after #delay seconds if no active connections are present (no players). Use #exist_code or 0 as program exist code.');
REPLACE INTO `command` VALUES ('server idleshutdown cancel', 8, 'Syntax: .server idleshutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.');
REPLACE INTO `command` VALUES ('server info', 8, 'Syntax: .server info\r\n\r\nDisplay server version and the number of connected players.');
REPLACE INTO `command` VALUES ('server motd', 8, 'Syntax: .server motd\r\n\r\nShow server Message of the day.');
REPLACE INTO `command` VALUES ('server restart', 8, 'Syntax: .server restart #delay\r\n\r\nRestart the server after #delay seconds. Use #exist_code or 2 as program exist code.');
REPLACE INTO `command` VALUES ('server restart cancel', 8, 'Syntax: .server restart cancel\r\n\r\nCancel the restart/shutdown timer if any.');
REPLACE INTO `command` VALUES ('server set closed', 8, 'Syntax: server set closed on/off\r\n\r\nSets whether the world accepts new client connectsions.');
REPLACE INTO `command` VALUES ('server set loglevel', 8, 'Syntax: .server set loglevel $facility $name $loglevel. $facility can take the values: appender (a) or logger (l). $loglevel can take the values: disabled (0), trace (1), debug (2), info (3), warn (4), error (5) or fatal (6)');
REPLACE INTO `command` VALUES ('server set motd', 8, 'Syntax: .server set motd $MOTD\r\n\r\nSet server Message of the day.');
REPLACE INTO `command` VALUES ('server shutdown', 8, 'Syntax: .server shutdown #delay [#exit_code]\r\n\r\nShut the server down after #delay seconds. Use #exit_code or 0 as program exit code.');
REPLACE INTO `command` VALUES ('server shutdown cancel', 8, 'Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.');
REPLACE INTO `command` VALUES ('server togglequerylog', 8, '');
REPLACE INTO `command` VALUES ('setskill', 6, 'Syntax: .setskill #skill #level [#max]\r\n\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.');
REPLACE INTO `command` VALUES ('showarea', 8, 'Syntax: .showarea #areaid\r\n\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.');
REPLACE INTO `command` VALUES ('skirmish', 8, '');
REPLACE INTO `command` VALUES ('spect', 0, '');
REPLACE INTO `command` VALUES ('spect leave', 0, '');
REPLACE INTO `command` VALUES ('spect reset', 0, '');
REPLACE INTO `command` VALUES ('spect spectate', 0, '');
REPLACE INTO `command` VALUES ('spect version', 0, '');
REPLACE INTO `command` VALUES ('spect watch', 0, '');
REPLACE INTO `command` VALUES ('summon', 3, 'Syntax: .summon [$charactername]\r\n\r\nTeleport the given character to you. Character can be offline.');
REPLACE INTO `command` VALUES ('tele', 1, 'Syntax: .tele #location\r\n\r\nTeleport player to a given location.');
REPLACE INTO `command` VALUES ('tele add', 6, 'Syntax: .tele add $name\r\n\r\nAdd current your position to .tele command target locations list with name $name.');
REPLACE INTO `command` VALUES ('tele del', 6, 'Syntax: .tele del $name\r\n\r\nRemove location with name $name for .tele command locations list.');
REPLACE INTO `command` VALUES ('tele group', 6, 'Syntax: .tele group#location\r\n\r\nTeleport a selected player and his group members to a given location.');
REPLACE INTO `command` VALUES ('tele name', 1, 'Syntax: .tele name [#playername] #location\n\nTeleport the given character to a given location. Character can be offline.\n\nTo teleport to homebind, set #location to "$home" (without quotes).');
REPLACE INTO `command` VALUES ('ticket', 1, 'Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('ticket assign', 1, 'Usage: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.');
REPLACE INTO `command` VALUES ('ticket close', 2, 'Usage: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.');
REPLACE INTO `command` VALUES ('ticket closedlist', 2, 'Displays a list of closed GM tickets.');
REPLACE INTO `command` VALUES ('ticket comment', 2, 'Usage: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.');
REPLACE INTO `command` VALUES ('ticket complete', 2, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket delete', 4, 'Usage: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.');
REPLACE INTO `command` VALUES ('ticket escalate', 4, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket escalatedlist', 4, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket list', 1, 'Displays a list of open GM tickets.');
REPLACE INTO `command` VALUES ('ticket onlinelist', 1, 'Displays a list of open GM tickets whose owner is online.');
REPLACE INTO `command` VALUES ('ticket reset', 8, 'Syntax: .ticket reset\nRemoves all closed tickets and resets the counter, if no pending open tickets are existing.');
REPLACE INTO `command` VALUES ('ticket response', 4, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket response append', 4, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket response appendln', 4, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket togglesystem', 8, 'Syntax: ');
REPLACE INTO `command` VALUES ('ticket unassign', 8, 'Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.');
REPLACE INTO `command` VALUES ('ticket viewid', 1, 'Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.');
REPLACE INTO `command` VALUES ('ticket viewname', 1, 'Usage: .ticket viewname $creatorname. \r\nReturns details about specified ticket. Ticket must be open and not deleted.');
REPLACE INTO `command` VALUES ('titles', 6, 'Syntax: ');
REPLACE INTO `command` VALUES ('titles add', 6, 'Syntax: .titles add #title\r\nAdd title #title (id or shift-link) to known titles list for selected player.');
REPLACE INTO `command` VALUES ('titles current', 6, 'Syntax: .titles current #title\r\nSet title #title (id or shift-link) as current selected titl for selected player. If title not in known title list for player then it will be added to list.');
REPLACE INTO `command` VALUES ('titles remove', 6, 'Syntax: .titles remove #title\r\nRemove title #title (id or shift-link) from known titles list for selected player.');
REPLACE INTO `command` VALUES ('titles set', 6, 'Syntax: ');
REPLACE INTO `command` VALUES ('titles set mask', 6, 'Syntax: .titles set mask #mask\r\n\r\nAllows user to use all titles from #mask.\r\n\r\n #mask=0 disables the title-choose-field');
REPLACE INTO `command` VALUES ('unaura', 5, 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.');
REPLACE INTO `command` VALUES ('unban', 7, 'Syntax: .unban $subcommand\nType .unban to see the list of possible subcommands or .help unban $subcommand to see info on subcommands');
REPLACE INTO `command` VALUES ('unban account', 7, 'Syntax: .unban account $Name\r\nUnban accounts for account name pattern.');
REPLACE INTO `command` VALUES ('unban character', 7, 'Syntax: .unban character $Name\r\nUnban accounts for character name pattern.');
REPLACE INTO `command` VALUES ('unban ip', 7, 'Syntax : .unban ip $Ip\r\nUnban accounts for IP pattern.');
REPLACE INTO `command` VALUES ('unban playeraccount', 8, '');
REPLACE INTO `command` VALUES ('unbindsight', 8, 'Syntax: .unbindsight\r\n\r\nRemoves bound vision. Cannot be used while currently possessing a target.');
REPLACE INTO `command` VALUES ('unfreeze', 4, 'Syntax: .unfreeze (#player)\r\n"Unfreezes" #player and enables his chat again. When using this without #name it will unfreeze your target.');
REPLACE INTO `command` VALUES ('unlearn', 8, 'Syntax: .unlearn #spell [all]\r\n\r\nUnlearn for selected player a spell #spell.  If \'all\' provided then all ranks unlearned.');
REPLACE INTO `command` VALUES ('unmute', 4, 'Syntax: .unmute [$playerName]\r\n\r\nRestore chat messaging for any character from account of character $playerName (or selected). Character can be ofline.');
REPLACE INTO `command` VALUES ('unpossess', 8, 'Syntax: .unpossess\r\n\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.');
REPLACE INTO `command` VALUES ('unstuck', 1, 'Syntax: .unstuck $playername [inn/graveyard/startzone]\n\nTeleports specified player to specified location. Default location is player\'s current hearth location.');
REPLACE INTO `command` VALUES ('wchange', 8, 'Syntax: .wchange #weathertype #status\r\n\r\nSet current weather to #weathertype with an intensity of #status.\r\n\r\n#weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.');
REPLACE INTO `command` VALUES ('whispers', 1, 'Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use trinityd.conf setting.');
REPLACE INTO `command` VALUES ('wp', 6, 'Syntax: wp $subcommand\n Type .wp to see a list of possible subcommands\n or .help wp $subcommand to see info on the subcommand.');
REPLACE INTO `command` VALUES ('wp add', 6, 'Syntax: .wp add\r\n\r\nAdd a waypoint for the selected creature at your current position.');
REPLACE INTO `command` VALUES ('wp event', 6, 'Syntax: .wp event $subcommand\nType .path event to see the list of possible subcommands or .help path event $subcommand to see info on subcommands.');
REPLACE INTO `command` VALUES ('wp load', 6, 'Syntax: .wp load $pathid\nLoad pathid number for selected creature. Creature must have no waypoint data.');
REPLACE INTO `command` VALUES ('wp modify', 6, 'Syntax: ');
REPLACE INTO `command` VALUES ('wp reload', 6, 'Syntax: .wp reload $pathid\nLoad path changes ingame - IMPORTANT: must be applied first for new paths before .wp load #pathid ');
REPLACE INTO `command` VALUES ('wp show', 6, 'Syntax: .wp show $option\nOptions:\non $pathid (or selected creature with loaded path) - Show path\noff - Hide path\ninfo $slected_waypoint - Show info for selected waypoint.');
REPLACE INTO `command` VALUES ('wp unload', 6, 'Syntax: .wp unload\nUnload path for selected creature.');
REPLACE INTO `command` VALUES ('wpgps', 8, 'Syntax: .wpgps\n\nOutput current position to sql developer log as partial SQL query to be used in pathing');
